runroom.base.route.demo.es:
    path: /
    defaults:
        _controller: runroom.demo.controller.demo:index
        _locale: es

runroom.base.route.demo.en:
    path: /en
    defaults:
        _controller: runroom.demo.controller.demo:index
        _locale: en
