services:
    # Controllers
    runroom.demo.controller.demo:
        class: Runroom\DemoBundle\Controller\DemoController
        arguments:
            templating: '@templating'
            service: '@runroom.demo.service.demo'

    # Services
    runroom.demo.service.demo:
        class: Runroom\DemoBundle\Service\DemoService
        arguments:
            repository: '@runroom.demo.repository.demo'

    # Repositories
    runroom.demo.repository.demo:
        class: Runroom\DemoBundle\Repository\DemoRepository
        arguments:
            doctrine: '@doctrine.orm.entity_manager'
