services:
    runroom.translations.admin.message:
        class: Runroom\TranslationsBundle\Admin\MessageAdmin
        arguments: [~, Runroom\TranslationsBundle\Entity\Message, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Messages' }
