services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Runroom\TranslationsBundle\Service\MessageService:
        arguments:
            $repository: '@Doctrine\ORM\EntityRepository'
            $translator: '@translator'

    Doctrine\ORM\EntityRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - Runroom\TranslationsBundle\Entity\Message

    Runroom\TranslationsBundle\Twig\MessageExtension:
        tags: ['twig.extension']
