services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Runroom\TranslationsBundle\:
        resource: '../../*'

    Runroom\TranslationsBundle\Service\MessageService:
        bind:
            $repository: '@Doctrine\ORM\EntityRepository'

    Doctrine\ORM\EntityRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments: [Runroom\TranslationsBundle\Entity\Message]
