services:
    runroom.translations.twig.message:
        class: Runroom\TranslationsBundle\Twig\MessageExtension
        public: false
        arguments:
            repository: @runroom.translations.repository.message
            translator: @translator
        tags:
            - { name: twig.extension }

    runroom.translations.repository.message:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Runroom\TranslationsBundle\Entity\Message