services:
    # Services
    runroom.translations.service.message:
        class: Runroom\TranslationsBundle\Service\MessageService
        arguments:
            repository: '@runroom.translations.repository.message'
            translator: '@translator'

    # Repositories
    runroom.translations.repository.message:
        class: Doctrine\ORM\EntityRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments:
            - Runroom\TranslationsBundle\Entity\Message

    # Extensions
    runroom.translations.twig.message:
        class: Runroom\TranslationsBundle\Twig\MessageExtension
        arguments:
            service: '@runroom.translations.service.message'
        tags:
            -
                name: twig.extension
