services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Runroom\TranslationsBundle\:
        resource: ../../*

    Doctrine\ORM\EntityRepository:
        factory: ['@Doctrine\ORM\EntityManagerInterface', getRepository]
        arguments: [Runroom\TranslationsBundle\Entity\Message]
