runroom.static_page.route.static.static.en:
    path: /{slug}
    defaults:
        _controller: runroom.static_page.controller.static_page:staticPage
        _locale: en
    requirements:
        slug: ^(?!backoffice).*
