runroom.static_page.route.static.static.ca:
    path: /{slug}
    defaults:
        _controller: runroom.static_page.controller.static_page:staticPage
        _locale: ca
    requirements:
        slug: ^(?!backoffice).*
