runroom.static_page.route.static.static.es:
    path: /es/{staticPageSlug}
    defaults:
        _controller: runroom.static_page.controller.static_page:staticPage
        _locale: es
    requirements:
        staticPageSlug: .*
