runroom.static_page.route.static.static.es:
    path: /{slug}
    defaults:
        _controller: runroom.static_page.controller.static_page:staticPage
        _locale: es
    requirements:
        slug: ^(?!backoffice).*
