runroom.static_page.route.static.static.en:
    path: /{static_page_slug}
    defaults:
        _controller: runroom.static_page.controller.static_page:staticPage
        _locale: en
    requirements:
        static_page_slug: .*
