runroom.static_page.route.static.static.en:
    path: /{slug}
    defaults:
        _controller: Runroom\StaticPageBundle\Controller\StaticPageController:staticPage
        _locale: en
    requirements:
        slug: ^(?!backoffice).*
