runroom.static_page.route.static.static.ca:
    path: /{slug}
    defaults:
        _controller: Runroom\StaticPageBundle\Controller\StaticPageController:staticPage
        _locale: ca
    requirements:
        slug: ^(?!backoffice).*
