runroom.static_page.route.static.static.es:
    path: /es/{static_page_slug}
    defaults:
        _controller: runroom.static_page.controller.static_page:staticPage
        _locale: es
    requirements:
        static_page_slug: .*
