---
- name: Create directories
  become: false
  file:
    path: '/home/ubuntu/{{ item.folder }}'
    state: directory
  with_items: '{{ server.links }}'
  when: server.links is defined

- name: Create symbolic links
  become: false
  file:
    src: '/home/ubuntu/{{ item.folder }}'
    dest: '{{ item.dest }}/{{ item.folder }}'
    state: link
  with_items: '{{ server.links }}'
  when: server.links is defined
