framework:
    assets:
        version: '%assets_version%'
        version_format: '%%s?v=%%s'
    secret: '%secret%'
    form: true
    csrf_protection: true
    templating:
        engines: [twig]
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    cache:
        app: cache.adapter.apcu
