sonata_doctrine_orm_admin:
    templates:
        types:
            list:
                image: '@SonataMedia/MediaAdmin/list_image.html.twig'
            show:
                image: sonata/show_image.html.twig
