twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes:
        - '@SonataMedia/Form/media_widgets.html.twig'
        - '@SonataCore/Form/datepicker.html.twig'
        - sonata/custom_widgets.html.twig
    globals:
        xDefaultLocale: '%x_default_locale%'
        gtmId: '%gtm_id%'
        cookiesDefaultDomain: '%cookies_default_domain%'
        cookiesSecure: '%cookies_secure%'
