archetype.base.route.demo.en:
    path: /
    defaults:
        _controller: archetype.demo.controller.demo:index
        _locale: en

archetype.base.route.demo.es:
    path: /es
    defaults:
        _controller: archetype.demo.controller.demo:index
        _locale: es

archetype.base.route.demo.ca:
    path: /ca
    defaults:
        _controller: archetype.demo.controller.demo:index
        _locale: ca
