archetype.base.route.demo.en:
    path: /
    defaults:
        _controller: archetype.demo.controller.demo:index
        _locale: en

archetype.base.route.demo.ea:
    path: /es
    defaults:
        _controller: archetype.demo.controller.demo:index
        _locale: es
