archetype.demo.route.demo:
    path: /
    controller: Archetype\DemoBundle\Controller\DemoController:index

archetype.demo.route.ajax.form:
    path: /ajax-form
    controller: Archetype\DemoBundle\Controller\DemoController:ajaxForm

archetype.demo.contact:
    path: /contact
    methods: [POST]
    controller: Archetype\DemoBundle\Controller\DemoController:contactData
