services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Archetype\DemoBundle\:
        resource: ../../*

    Archetype\DemoBundle\Controller\:
        resource: ../../Controller
        public: true
        tags: [controller.service_arguments]
