services:
    # Controllers
    archetype.demo.controller.demo:
        class: Archetype\DemoBundle\Controller\DemoController
        public: true
        arguments:
            templating: '@templating'
            service: '@archetype.demo.service.demo'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]

    # Services
    archetype.demo.service.demo:
        class: Archetype\DemoBundle\Service\DemoService
        arguments:
            repository: '@archetype.demo.repository.book'

    # Repositories
    archetype.demo.repository.book:
        class: Archetype\DemoBundle\Repository\BookRepository
        arguments:
            doctrine: '@doctrine.orm.entity_manager'
