services:
    # Controllers
    archetype.demo.controller.demo:
        class: Archetype\DemoBundle\Controller\DemoController
        arguments:
            templating: @templating
            service: @archetype.demo.service.demo
        calls:
            - [setEventDispatcher, [@event_dispatcher]]

    # Services
    archetype.demo.service.demo:
        class: Archetype\DemoBundle\Service\DemoService
        arguments:
            repository: @archetype.demo.repository.demo

    # Repositories
    archetype.demo.repository.demo:
        class: Archetype\DemoBundle\Repository\DemoRepository
        arguments:
            doctrine: @doctrine.orm.entity_manager
