runroom.static_page.route.static.es:
    resource: '@RunroomStaticPageBundle/Resources/config/static/static.es.yml'
    prefix: /

runroom.static_page.route.static.en:
    resource: '@RunroomStaticPageBundle/Resources/config/static/static.en.yml'
    prefix: /
