runroom.static_page.route.es:
    resource: routes/es.yml
    prefix: /es
    defaults:
        _locale: es

runroom.static_page.route.ca:
    resource: routes/ca.yml
    prefix: /ca
    defaults:
        _locale: ca

# Must be the last one
runroom.static_page.route.en:
    resource: routes/en.yml
    prefix: /
    defaults:
        _locale: en
