runroom.static_page.route.static.es:
    resource: '@RunroomStaticPageBundle/Resources/config/static/static.es.yml'
    prefix: /es

runroom.static_page.route.static.ca:
    resource: '@RunroomStaticPageBundle/Resources/config/static/static.ca.yml'
    prefix: /ca

# Must be the last one
runroom.static_page.route.static.en:
    resource: '@RunroomStaticPageBundle/Resources/config/static/static.en.yml'
    prefix: /
