services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Runroom\StaticPageBundle\:
        resource: ../../*

    Runroom\StaticPageBundle\Controller\:
        resource: ../../Controller
        public: true
        tags: [controller.service_arguments]

    _instanceof:
        Runroom\BaseBundle\Service\MetaInformation\MetaInformationProviderInterface:
            tags: [base.meta_information]
        Runroom\BaseBundle\Service\AlternateLinks\AlternateLinksProviderInterface:
            tags: [base.alternate_links]
