services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'
            $xdefaultLocale: '%xdefault_locale%'

    _instanceof:
        Runroom\BaseBundle\Service\MetaInformation\MetaInformationProviderInterface:
            tags: ['base.meta_information']
        Runroom\BaseBundle\Service\AlternateLinksProvider\AlternateLinksProviderInterface:
            tags: ['base.alternate_links']

    Runroom\StaticPageBundle\:
        resource: '../../*'

    Runroom\StaticPageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']
