services:
    # Controllers
    runroom.static_page.controller.static_page:
        class: Runroom\StaticPageBundle\Controller\StaticPageController
        arguments:
            templating: @templating
            service: @runroom.static_page.service.static_page
        calls:
            - [setEventDispatcher, [@event_dispatcher]]

    # Services
    runroom.static_page.service.static_page:
        class: Runroom\StaticPageBundle\Service\StaticPageService
        arguments:
            repository: @runroom.static_page.repository.static_page

    runroom.static_page.service.static_page_meta_information_provider:
        class: Runroom\StaticPageBundle\Service\StaticPageMetaInformationProvider
        arguments:
            repository: @runroom.base.repository.meta_information
        tags:
            -
                name: base.meta_information

    runroom.static_page.service.static_page_alternate_links_provider:
        class: Runroom\StaticPageBundle\Service\StaticPageAlternateLinksProvider
        arguments:
            router: @router
            request_stack: @request_stack
            locales: '%locales%'
        tags:
            -
                name: base.alternate_links

    # Repositories
    runroom.static_page.repository.static_page:
        class: Runroom\StaticPageBundle\Repository\StaticPageRepository
        arguments:
            doctrine: @doctrine.orm.entity_manager
