services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'

    Runroom\StaticPageBundle\:
        resource: '../../*'

    Runroom\StaticPageBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Runroom\StaticPageBundle\Service\StaticPageMetaInformationProvider:
        tags: ['base.meta_information']

    Runroom\StaticPageBundle\Service\StaticPageAlternateLinksProvider:
        tags: ['base.alternate_links']
