runroom.static_page.route.static.en:
    path: /{slug}
    controller: Runroom\StaticPageBundle\Controller\StaticPageController:staticPage
    requirements:
        slug: ^(?!backoffice|styleguide).*
