runroom.static_page.route.static.static.es:
    path: /{slug}
    defaults:
        _controller: Runroom\StaticPageBundle\Controller\StaticPageController:staticPage
    requirements:
        slug: ^(?!backoffice).*
