_wdt:
    resource: '@WebProfilerBundle/Resources/config/routing/wdt.xml'
    trailing_slash_on_root: false
    prefix: /_wdt

_profiler:
    resource: '@WebProfilerBundle/Resources/config/routing/profiler.xml'
    trailing_slash_on_root: false
    prefix: /_profiler
