imports:
    - { resource: config.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        driver: pdo_sqlite
        server_version: 5.6
        path: ':memory:'
        memory: true
