parameters:
    locale: en
    x_default_locale: en
    locales: [en, es, ca]
    assets_version: 1.0.0
    container.autowiring.strict_mode: true
    container.dumper.inline_class_loader: true

imports:
    - { resource: parameters.yml }
    - { resource: services.yml }
    - { resource: packages/ }
