imports:
    - { resource: parameters.yml }

    # Basic
    - { resource: basic/framework.yml }
    - { resource: basic/security.yml }
    - { resource: basic/doctrine.yml }
    - { resource: basic/swiftmailer.yml }
    - { resource: basic/twig.yml }
    - { resource: basic/ivory_ck_editor.yml }
    - { resource: basic/extra.yml }

    # Sonata conf
    - { resource: sonata/sonata_admin.yml }
    - { resource: sonata/sonata_block.yml }
    - { resource: sonata/sonata_media.yml }
    - { resource: sonata/sonata_doctrine_orm_admin.yml }
    - { resource: sonata/sonata_formatter.yml }
    - { resource: sonata/sonata_user.yml }

    # FOS conf
    - { resource: fos/fos_user.yml }
