_frontoffice:
    resource: routing/routing_frontoffice.yml
    prefix: /

_backoffice:
    resource: routing/routing_backoffice.yml
    prefix: /backoffice

# Must be the last one
runroom_static_page:
    resource: '@RunroomStaticPageBundle/Resources/config/routing.yml'
    prefix: /
