parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: {{ mysql.database }}
    database_user: {{ mysql.user }}
    database_password: {{ mysql.password }}

    mailer_transport: sendmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: null
    mailer_user: null
    mailer_password: null
    mailer_from: noreply@symfony.local
    mailer_bcc: []

    secret: {{ symfony.secret }}
