parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: {{ mysql.database }}
    database_user: {{ mysql.user }}
    database_password: {{ mysql.password }}

    mailer_transport: sendmail
    mailer_encryption: ssl
    mailer_auth_mode: login
    mailer_host: null
    mailer_user: null
    mailer_password: null
    mailer_from: noreply@{{ webserver.name }}
    mailer_bcc: []

    secret: c81e356a07607848a59e492f824b3fc3bbe61542

    gtm_id: GTM-KTPM543

    cookies_default_domain: .{{ webserver.name }}
