sonata_media:
    default_context: default
    db_driver: doctrine_orm
    contexts:
        default:
            providers:
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats: ~

    cdn: ~

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true

    providers:
        image: ~
