runroom.base.route.static.ca:
    path: /ca/{static_page_slug}
    defaults:
        _controller: runroom.base.controller.static_page:staticPage
        _locale: ca
    requirements:
        static_page_slug: .*
