---
server:
  packages: [zip, sqlite3]
  timezone: Europe/Madrid
  locale: es_ES.UTF-8
  swap_size: 2048M
  swap_settings:
    - { key: vm.swappiness, value: 10 }
    - { key: vm.vfs_cache_pressure, value: 50 }
  links:
    - { folder: vendor, dest: /vagrant }
    - { folder: node_modules, dest: /vagrant }
    - { folder: cache, dest: /vagrant/var }
    - { folder: logs, dest: /vagrant/var }
apache:
  docroot: /vagrant/web
  servername: symfony.dev
  serveralias: []
  modules: [rewrite, ssl]
mysql:
  database: symfony
  user: symfony
  password: symfony
  dump: ''
php:
  version: 7.0
  extensions: [intl, mcrypt, curl, mysql, sqlite3, gd, xml, zip, mbstring, bz2]
  extras: [php-xdebug, php-apcu, php-apcu-bc]
  settings:
    - { setting: date.timezone, value: Europe/Madrid }
    - { setting: opcache.enable, value: 1 }
    - { setting: opcache.max_accelerated_files, value: 20000 }
    - { setting: realpath_cache_size, value: 5M }
    - { setting: realpath_cache_ttl, value: 7200 }
    - { setting: upload_max_filesize, value: 20M }
    - { setting: post_max_size, value: 20M }
symfony:
  secret: c81e356a07607848a59e492f824b3fc3bbe61542
  permission_dirs: [cache, logs]
  files:
    - { file: parameters.yml, dest: /vagrant/app/config }
    - { file: .htaccess, dest: /vagrant/web }
composer:
  packages:
    - { package: hirak/prestissimo }
node:
  source: 6.x
  packages:
    - { package: npm-check-updates }
    - { package: gulp, version: 3.9.1 }
