---
- name: Download symfony cli
  get_url:
    url: https://get.symfony.com/cli/installer
    dest: /tmp/symfony-installer

- name: Install symfony cli
  command: 'bash /tmp/symfony-installer'
  args:
    creates: '{{ ansible_env.HOME }}/.symfony/bin/symfony'

- name: Ensure directories exists
  file:
    path: '{{ ansible_env.HOME }}/{{ item }}'
    state: directory
  with_items: '{{ symfony.permission_dirs }}'
  when: symfony.permission_dirs is defined

- name: Set correct permissions
  become: true
  acl:
    name: '{{ ansible_env.HOME }}/{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rwX
    default: '{{ item[2] }}'
    recursive: yes
    state: present
  with_nested:
    - '{{ symfony.permission_dirs }}'
    - [www-data, '{{ ansible_env.USER }}']
    - [no, yes]
  when: symfony.permission_dirs is defined
