---
- name: Download symfony cli
  get_url:
    url: https://get.symfony.com/cli/installer
    dest: /tmp/symfony-installer

- name: Install symfony cli
  command: 'bash /tmp/symfony-installer'
  args:
    creates: '{{ ansible_env.HOME }}/.symfony/bin/symfony'

- name: Create symfony files
  template:
    src: '{{ item.file }}'
    dest: '/tmp/{{ item.file }}'
  with_items: '{{ symfony.files }}'
  when: symfony.files is defined

- name: Move symfony files
  command: 'cp /tmp/{{ item.file }} {{ item.dest }}/{{ item.file }}'
  with_items: '{{ symfony.files }}'
  when: symfony.files is defined

- name: Set correct permissions
  become: true
  acl:
    name: '{{ ansible_env.HOME }}/{{ item[0] }}'
    entity: '{{ item[1] }}'
    etype: user
    permissions: rwX
    default: '{{ item[2] }}'
    recursive: yes
    state: present
  with_nested:
    - '{{ symfony.permission_dirs }}'
    - [www-data, '{{ ansible_env.USER }}']
    - [no, yes]
  when: symfony.permission_dirs is defined
