---
- name: Create parameters.yml
  template:
    src: parameters.yml
    dest: /tmp/parameters.yml

- name: Move parameters.yml
  command: cp /tmp/parameters.yml /vagrant/app/config/parameters.yml

- name: Create .htaccess
  template:
    src: .htaccess
    dest: /tmp/.htaccess

- name: Move .htaccess
  command: cp /tmp/.htaccess /vagrant/web/.htaccess

- name: Create app_dev.php
  template:
    src: app_dev.php
    dest: /tmp/app_dev.php

- name: Move app_dev.php
  command: cp /tmp/app_dev.php /vagrant/web/app_dev.php
