---
- name: Set correct permissions
  acl:
    name: '/home/ubuntu/{{ item }}'
    entity: www-data
    etype: user
    permissions: rwX
    default: no
    recursive: yes
    state: present
  with_items:
    - cache
    - logs

- name: Set correct permissions
  acl:
    name: '/home/ubuntu/{{ item }}'
    entity: www-data
    etype: user
    permissions: rwX
    default: yes
    recursive: yes
    state: present
  with_items:
    - cache
    - logs

- name: Set correct permissions
  acl:
    name: '/home/ubuntu/{{ item }}'
    entity: ubuntu
    etype: user
    permissions: rwX
    default: no
    recursive: yes
    state: present
  with_items:
    - cache
    - logs

- name: Set correct permissions
  acl:
    name: '/home/ubuntu/{{ item }}'
    entity: ubuntu
    etype: user
    permissions: rwX
    default: yes
    recursive: yes
    state: present
  with_items:
    - cache
    - logs
