---
- name: Add ppa repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Update apt
  apt:
    update_cache: yes

- name: Install php
  apt:
    pkg: 'php{{ php.version }}'
    state: latest

- name: Install php packages
  apt:
    pkg: 'php{{ php.version }}-{{ item }}'
    state: latest
  with_items: '{{ php.packages }}'
  when: php.packages is defined

- name: Disable xdebug
  shell: phpdismod xdebug

- include: php-apache.yml
- include: php-cli.yml
