---
- name: Add ppa repository
  apt_repository:
    repo: ppa:ondrej/php

- name: Update apt
  apt:
    update_cache: yes

- name: Install php
  apt:
    pkg: 'php{{ php.version }}'
    state: latest

- name: Install php extensions
  apt:
    pkg: 'php{{ php.version }}-{{ item }}'
    state: latest
  with_items: '{{ php.extensions }}'
  when: php.extensions is defined
  notify: Restart Apache

- name: Install php extras
  apt:
    pkg: '{{ item }}'
    state: latest
  with_items: '{{ php.extras }}'
  when: php.extras is defined
  notify: Restart Apache

- name: Ensure php link
  file:
    force: yes
    src: '/usr/bin/php{{ php.version }}'
    path: /etc/alternatives/php
    state: link

- name: Disable xdebug
  shell: phpdismod xdebug

- include: php-apache.yml
- include: php-cli.yml
