---
- name: Add ppa repository
  become: true
  apt_repository:
    repo: ppa:ondrej/php

- name: Install php
  become: true
  apt:
    name: 'php{{ php.version }}-fpm'
    state: latest

- name: Install php extensions
  become: true
  apt:
    name: 'php{{ php.version }}-{{ item }}'
    state: latest
  with_items: '{{ php.extensions }}'
  when: php.extensions is defined
  notify: Restart fpm

- name: Install php extras
  become: true
  apt:
    name: '{{ item }}'
    install_recommends: no
    state: latest
  with_items: '{{ php.extras }}'
  when: php.extras is defined
  notify: Restart fpm

- name: Disable xdebug
  become: true
  command: phpdismod xdebug
  args:
    removes: '/etc/php/{{ php.version }}/fpm/conf.d/20-xdebug.ini'
  notify: Restart fpm

- name: Modify settings on fpm php.ini
  become: true
  lineinfile:
    dest: '/etc/php/{{ php.version }}/fpm/php.ini'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.settings }}'
  notify: Restart fpm

- name: Modify settings on fpm www.conf
  become: true
  lineinfile:
    dest: '/etc/php/{{ php.version }}/fpm/pool.d/www.conf'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.fpm }}'
  notify: Restart fpm

- name: Modify settings on cli php.ini
  become: true
  lineinfile:
    dest: '/etc/php/{{ php.version }}/cli/php.ini'
    regexp: ';?{{ item.setting }} ?=.*'
    line: '{{ item.setting }} = {{ item.value }}'
  with_items: '{{ php.settings }}'
  notify: Restart fpm
