---
- name: Open on /vagrant by default
  lineinfile:
    dest: /home/vagrant/.bashrc
    state: present
    line: 'cd /vagrant'

- name: Install vendors
  composer:
    no_dev: no
    optimize_autoloader: no
    working_dir: /vagrant
  become: false
