---
- name: Database migrations
  become: false
  command: php app/console doctrine:migrations:migrate --no-interaction
  args:
    chdir: /vagrant

- name: Add bash aliases
  become: false
  template:
    src: .bash_aliases
    dest: /home/vagrant/.bash_aliases

- name: Open on /vagrant by default
  become: false
  lineinfile:
    dest: /home/vagrant/.bashrc
    state: present
    line: 'cd /vagrant'
