---
- name: Download nodesource setup
  get_url:
    url: 'http://deb.nodesource.com/setup_{{ node.source }}'
    mode: 0777
    dest: /tmp/node.sh

- name: Setup nodesource apt
  shell: /tmp/node.sh

- name: Install node
  apt:
    pkg: nodejs
    state: latest

- name: Install global npm packages
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{ node.packages }}'
