---
- name: Import the NodeSource GPG key into apt
  apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x1655A0AB68576280
    id: "68576280"
    state: present

- name: Add NodeSource deb repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ node.source }}'
    state: present

- name: Install Node.js
  apt:
    pkg:
      - nodejs
    state: latest

- name: Install global npm packages
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{ node.packages }}'

- name: Create symbolic links
  become: false
  file:
    src: '/home/vagrant/{{ item.folder }}'
    dest: '{{ item.dest }}/{{ item.folder }}'
    state: link
  with_items:
    - { folder: node_modules, dest: /vagrant }
