---
- name: Set correct permissions
  acl:
    name: '/home/vagrant/{{ item }}'
    entity: www-data
    etype: user
    permissions: rwX
    default: no
    recursive: yes
    state: present
  with_items:
    - node_modules

- name: Set correct permissions
  acl:
    name: '/home/vagrant/{{ item }}'
    entity: www-data
    etype: user
    permissions: rwX
    default: yes
    recursive: yes
    state: present
  with_items:
    - node_modules

- name: Set correct permissions
  acl:
    name: '/home/vagrant/{{ item }}'
    entity: vagrant
    etype: user
    permissions: rwX
    default: no
    recursive: yes
    state: present
  with_items:
    - node_modules

- name: Set correct permissions
  acl:
    name: '/home/vagrant/{{ item }}'
    entity: vagrant
    etype: user
    permissions: rwX
    default: yes
    recursive: yes
    state: present
  with_items:
    - node_modules
