---
- hosts: all
  sudo: true
  vars_files:
    - vars/all.yml
    - vars/secure.yml
  roles:
    - server
    - vagrant_local
    - apache
    - mysql
    - sqlite
    - php
    - phpmyadmin
    - node
    - composer
    - app
