services:
    runroom.base.admin.meta_information:
        class: Runroom\BaseBundle\Admin\MetaInformationAdmin
        arguments: [ ~, Runroom\BaseBundle\Entity\MetaInformation, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SEO }

    runroom.base.admin.entity_meta_information:
        class: Runroom\BaseBundle\Admin\EntityMetaInformationAdmin
        arguments: [ ~, Runroom\BaseBundle\Entity\EntityMetaInformation, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Entity SEO }

    runroom.base.admin.static_page:
        class: Runroom\BaseBundle\Admin\StaticPageAdmin
        arguments: [ ~, Runroom\BaseBundle\Entity\StaticPage, PixSortableBehaviorBundle:SortableAdmin ]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Páginas estáticas }
        calls:
            - [ setPositionService, [@pix_sortable_behavior.position]]
