services:
    runroom.base.admin.meta_information:
        class: Runroom\BaseBundle\Admin\MetaInformationAdmin
        arguments: [~, Runroom\BaseBundle\Entity\MetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: SEO }

    runroom.base.admin.entity_meta_information:
        class: Runroom\BaseBundle\Admin\EntityMetaInformationAdmin
        arguments: [~, Runroom\BaseBundle\Entity\EntityMetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Entity SEO }
