services:
    runroom.base.admin.meta_information:
        class: Runroom\BaseBundle\Admin\MetaInformationAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\MetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'SEO' }

    runroom.base.admin.entity_meta_information:
        class: Runroom\BaseBundle\Admin\EntityMetaInformationAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\EntityMetaInformation, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Entity SEO' }

    runroom.base.admin.gallery:
        class: Runroom\BaseBundle\Admin\GalleryAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\Gallery, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Gallery' }

    runroom.base.admin.gallery_image:
        class: Runroom\BaseBundle\Admin\GalleryImageAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\GalleryImage, SortableBehaviorBundle:SortableAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'GalleryImage' }

    runroom.base.admin.user:
        class: Runroom\BaseBundle\Admin\UserAdmin
        public: true
        arguments: [~, Runroom\BaseBundle\Entity\User, ~]
        calls:
            - [setUserManager, ['@fos_user.user_manager']]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'User' }
