services:
    # Controllers
    runroom.base.controller.styleguide:
        class: Runroom\BaseBundle\Controller\StyleguideController
        arguments:
            templating: @templating

    runroom.base.controller.exception:
        class: Runroom\BaseBundle\Controller\ExceptionController
        arguments:
            templating: @templating
        calls:
            - [setEventDispatcher, [@event_dispatcher]]

    runroom.base.controller.static_page:
        class: Runroom\BaseBundle\Controller\StaticPageController
        arguments:
            templating: @templating
            service: @runroom.base.service.static_page
        calls:
            - [setEventDispatcher, [@event_dispatcher]]

    # Services
    runroom.base.service.meta_information:
        class: Runroom\BaseBundle\Service\MetaInformationService
        arguments:
            request_stack: @request_stack
            defualt_provider: @runroom.base.service.meta_information_provider.default
        tags:
            -
                name: kernel.event_listener
                event: runroom.events.page.render
                method: onPageEvent

    runroom.base.service.meta_information_provider.default:
        class: Runroom\BaseBundle\Service\MetaInformationProvider\DefaultMetaInformationProvider
        arguments:
            repository: @runroom.base.repository.meta_information

    runroom.base.service.meta_information_provider.not_found:
        class: Runroom\BaseBundle\Service\MetaInformationProvider\NotFoundMetaInformationProvider
        arguments:
            repository: @runroom.base.repository.meta_information

    runroom.base.service.meta_information_provider.static_page:
        class: Runroom\BaseBundle\Service\MetaInformationProvider\StaticPageMetaInformationProvider
        arguments:
            repository: @runroom.base.repository.meta_information
        tags:
            -
                name: base.meta_information

    runroom.base.service.alternate_links:
        class: Runroom\BaseBundle\Service\AlternateLinksService
        arguments:
            request_stack: @request_stack
            default_provider: @runroom.base.service.alternate_links_provider.default
        tags:
            -
                name: kernel.event_listener
                event: runroom.events.page.render
                method: onPageEvent

    runroom.base.service.alternate_links_provider.default:
        class: Runroom\BaseBundle\Service\AlternateLinksProvider\DefaultAlternateLinksProvider
        arguments:
            router: @router
            locales: '%locales%'

    runroom.base.service.alternate_links_provider.static_page:
        class: Runroom\BaseBundle\Service\AlternateLinksProvider\StaticPageAlternateLinksProvider
        arguments:
            router: @router
            locales: '%locales%'
        tags:
            -
                name: base.alternate_links

    runroom.base.service.static_page:
        class: Runroom\BaseBundle\Service\StaticPageService
        arguments:
            repository: @runroom.base.repository.static_page
        tags:
            -
                name: kernel.event_listener
                event: runroom.events.page.render
                method: onPageEvent

    # Repositories
    runroom.base.repository.meta_information:
        class: Runroom\BaseBundle\Repository\MetaInformationRepository
        arguments:
            doctrine: @doctrine.orm.entity_manager

    runroom.base.repository.static_page:
        class: Runroom\BaseBundle\Repository\StaticPageRepository
        arguments:
            doctrine: @doctrine.orm.entity_manager

    # Form
    runroom.base.form.type.media:
        class: Runroom\BaseBundle\Form\Type\MediaType
        arguments:
            pool: @sonata.media.pool
            class: Application\Sonata\MediaBundle\Entity\Media
        tags:
            -
                name: form.type
                alias: media_type

    # Extensions
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            -
                name: twig.extension
