services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'

    Runroom\BaseBundle\:
        resource: '../../*'

    Runroom\BaseBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Runroom\BaseBundle\Service\MailService:
        bind:
            $from: '%mailer_from%'
            $bcc: '%mailer_bcc%'

    Runroom\BaseBundle\Service\MetaInformation\MetaInformationService:
        bind:
            $providers: !tagged base.meta_information

    Runroom\BaseBundle\Service\AlternateLinks\AlternateLinksService:
        bind:
            $providers: !tagged base.alternate_links

    Runroom\BaseBundle\Service\PageRendererService:
        bind:
            $pageViewModel: '@runroom.base.page_view_model'

    Runroom\BaseBundle\Service\InternalIpService:
        bind:
            $internalIps: '%internal_ips%'

    runroom.base.page_view_model: ~
