services:
    # Controllers
    runroom.base.controller.exception:
        class: Runroom\BaseBundle\Controller\ExceptionController
        arguments:
            templating: '@templating'
        calls:
            - [setEventDispatcher, ['@event_dispatcher']]

    # Services
    runroom.base.service.meta_information:
        class: Runroom\BaseBundle\Service\MetaInformationService
        arguments:
            request_stack: '@request_stack'
            default_provider: '@runroom.base.service.meta_information_provider.default'
        tags:
            -
                name: kernel.event_listener
                event: runroom.events.page.render
                method: onPageEvent

    runroom.base.service.meta_information_provider.default:
        class: Runroom\BaseBundle\Service\MetaInformationProvider\DefaultMetaInformationProvider
        arguments:
            repository: '@runroom.base.repository.meta_information'

    runroom.base.service.alternate_links:
        class: Runroom\BaseBundle\Service\AlternateLinksService
        arguments:
            request_stack: '@request_stack'
            default_provider: '@runroom.base.service.alternate_links_provider.default'
        tags:
            -
                name: kernel.event_listener
                event: runroom.events.page.render
                method: onPageEvent

    runroom.base.service.alternate_links_provider.default:
        class: Runroom\BaseBundle\Service\AlternateLinksProvider\DefaultAlternateLinksProvider
        arguments:
            router: '@router'
            request_stack: '@request_stack'
            locales: '%locales%'

    # Repositories
    runroom.base.repository.meta_information:
        class: Runroom\BaseBundle\Repository\MetaInformationRepository
        arguments:
            doctrine: '@doctrine.orm.entity_manager'

    # Extensions
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            -
                name: twig.extension
