services:
    # Controllers
    runroom.base.controller.styleguide:
        class: Runroom\BaseBundle\Controller\StyleguideController
        arguments:
            templating: '@templating'

    # Extensions
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
