services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'
            $pageViewModel: '@runroom.base.page_view_model'

    Runroom\BaseBundle\:
        resource: '../../*'

    Runroom\BaseBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Runroom\BaseBundle\Service\MetaInformationService:
        arguments:
            $requestStack: '@request_stack'
            $providers: !tagged base.meta_information
            $defaultProvider: '@Runroom\BaseBundle\Service\MetaInformationProvider\DefaultMetaInformationProvider'
        tags:
            - { name: kernel.event_listener, event: runroom.events.page.render, method: onPageEvent }

    Runroom\BaseBundle\Service\AlternateLinksService:
        arguments:
            $requestStack: '@request_stack'
            $providers: !tagged base.alternate_links
            $defaultProvider: '@Runroom\BaseBundle\Service\AlternateLinksProvider\DefaultAlternateLinksProvider'
        tags:
            - { name: kernel.event_listener, event: runroom.events.page.render, method: onPageEvent }

    runroom.base.page_view_model:
        class: ~

    Twig_Extensions_Extension_Intl:
        class: Twig_Extensions_Extension_Intl
        tags: ['twig.extension']

    Runroom\BaseBundle\Twig\UnescapeExtension:
        tags: ['twig.extension']
