services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $locales: '%locales%'
            $pageViewModel: '@runroom.base.page_view_model'

    Runroom\BaseBundle\:
        resource: '../../*'

    Runroom\BaseBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    Runroom\BaseBundle\Service\MetaInformationService:
        bind:
            $providers: !tagged base.meta_information
        tags:
            - { name: kernel.event_listener, event: runroom.events.page.render, method: onPageEvent }

    Runroom\BaseBundle\Service\AlternateLinksService:
        bind:
            $providers: !tagged base.alternate_links
        tags:
            - { name: kernel.event_listener, event: runroom.events.page.render, method: onPageEvent }

    runroom.base.page_view_model:
        class: ~
