# Doctrine Behaviors Configuration
knp_doctrine_behaviors:
    translatable: true
    timestampable: true

# A2lix Translation Form Configuration
a2lix_translation_form:
    locales: %locales%
    default_locale: %locale%
    required_locales: [%locale%]

# Stof Doctrine Extensions Configuration
stof_doctrine_extensions:
    orm:
        default:
            sortable: true
            sluggable: true

# Pix Sortable Behavior Configuration
pix_sortable_behavior:
    position_field:
        default: position
