ivory_ck_editor:
    default_config: config
    configs:
        config:
            toolbar:
                - ['Bold', 'Italic', 'Underline']
                - '-'
                - ['Link', 'Unlink', 'Anchor']
                - '-'
                - ['NumberedList', 'BulletedList', 'Blockquote']
                - '-'
                - ['Source']
