ivory_ck_editor:
    input_sync: true
    default_config: default
    configs:
        default:
            entities: false
            toolbar:
                - ['Bold', 'Italic', 'Underline']
                - '-'
                - ['Link', 'Unlink', 'Anchor']
                - '-'
                - ['NumberedList', 'BulletedList', 'Blockquote']
                - '-'
                - ['Image']
                - '-'
                - ['Source']
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: default
        messages:
            entities: false
            enterMode: CKEDITOR.ENTER_BR
            toolbar:
                - ['Bold', 'Italic', 'Underline']
                - '-'
                - ['Link', 'Unlink', 'Anchor']
                - '-'
                - ['NumberedList', 'BulletedList', 'Blockquote']
