security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    access_control:
        - { path: ^/backoffice/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/backoffice/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/backoffice/, role: ROLE_ADMIN }
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_SONATA_ADMIN
            - ROLE_SONATA_USER_ADMIN_USER_VIEW

        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_ALLOWED_TO_SWITCH

    access_decision_manager:
        strategy: unanimous

    providers:
        fos_userbundle:
            id: fos_user.user_manager

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        backoffice:
            pattern: /backoffice(.*)
            context: user
            switch_user: true
            form_login:
                provider: fos_userbundle
                login_path: /backoffice/login
                use_forward: false
                check_path: /backoffice/login_check
                failure_path: null
            logout:
                path: /backoffice/logout
                target: /backoffice
            remember_me:
                secret: '%secret%'
                lifetime: 604800
                path: /
            anonymous: true
