services:
    runroom.redirections.admin.redirect:
        class: Runroom\RedirectionsBundle\Admin\RedirectAdmin
        public: true
        arguments: [~, Runroom\RedirectionsBundle\Entity\Redirect, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: 'Redirects' }
