archetype_demo:
    resource: '@ArchetypeDemoBundle/Resources/config/routing.yml'
    prefix: /

runroom_entities:
    resource: '@RunroomEntitiesBundle/Resources/config/routing.yml'
    prefix: /

runroom_base:
    resource: '@RunroomBaseBundle/Resources/config/routing.yml'
    prefix: /
