archetype_demo:
    resource: '@ArchetypeDemoBundle/Resources/config/routing.yml'
    prefix: /

runroom_cookies:
    resource: '@RunroomCookiesBundle/Resources/config/routing.yml'
    prefix: /

# Must be the last one
runroom_static_page:
    resource: '@RunroomStaticPageBundle/Resources/config/routing.yml'
    prefix: /
